name: capitalview

networks:
  dev:

services:
  database:
    image: postgres:16.4-alpine
    environment:
      POSTGRES_DB: capitalview-local
      POSTGRES_USER: capitalview
      POSTGRES_PASSWORD: capitalview
    ports:
      - "5432:5432"
    # volumes:
      # - ./initdb:/var/lib/postgresql/data # if we want to add files like configuration or init.sql to the database
    networks:
      - dev

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    networks:
      - dev
    
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "4444:4444"
    depends_on:
      - database
    networks:
      - dev

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - backend
      - frontend
    networks:
      - dev

# enable to have data persist between container restarts
# volumes:
#   initdb:
#     driver: local
