name: capitalview

services:
  #.... frontend, nginx
  backend:
    #....
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "4444:4444"
    depends_on:
      - database

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: capitalview-local
      POSTGRES_USER: capitalview
      POSTGRES_PASSWORD: capitalview
    ports:
      - "5432:5432"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    profiles: [dev] # would run only when docker compose initialized with "--profile dev" attribute for "docker compose" command
                    # full request docker compose --profile dev up